import React from 'react'
import navbar from './Navbar.css'
import about from './About.css'
import contact from './Contact.css'
import login from './login.css'
import register from './register.css'
import university from './university.css'
import courseDetails from './EngCourseDetails.css'
import details from './Details.css'
import profile from './Profile.css'
import friend from './Friend.css'
import adminProfile from './Admin.css'
import adminNav from './AdminNav.css'
import sidebar from './Sidebar.css'
export{navbar , about , contact , login , register , university , courseDetails , details , profile , friend ,adminProfile,adminNav , sidebar}