package com.uni.info.service;

import com.uni.info.dto.UniversityDto;
import com.uni.info.entity.University;
import com.uni.info.exception.UniversityServiceException;
import com.uni.info.repository.UniversityRepo;
import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service

public class UniversityServiceImp implements UniversityService{
    @Autowired
    private UniversityRepo universityRepo;
    @Override
    public UniversityDto createUniversities(UniversityDto universityDto) throws UniversityServiceException {
        try {
            University university = new University();
            BeanUtils.copyProperties(universityDto, university);
            university.setUniName(universityDto.getUniName());
            University savedUniversity = universityRepo.save(university);

            // Update universityDto with the ID generated by the database
            universityDto.setUni_id(savedUniversity.getUni_id());

            return universityDto;
        } catch (Exception e) {
            throw new UniversityServiceException("Failed to create university: " + e.getMessage());
        }
    }

    @Override
    public List<University> getUniversities() {
        return universityRepo.findAll();
    }

    @Override
    public int updateuniname(Long uni_id, String uniName) {
//        Optional<University> entity = universityRepo.findById(uni_id);
//        System.out.println("repo : " + universityRepo.updateUniversity(uni_id,uniName));
        universityRepo.updateUniversity(uni_id, uniName);
        return 0;
    }
}
